"""
SYNTHETIC test PDFs, generated by code. Not filing data.

The company ("Synthetic Test Co.") and every number below are invented for tests; nothing here
claims to come from an SEC filing. Tables are drawn with ruled grid lines so that both Docling and
PyMuPDF's find_tables() detect them.
"""

from dataclasses import dataclass, field
from pathlib import Path

import pymupdf


@dataclass(frozen=True)
class SyntheticTable:
    title: str
    caption: str
    header: tuple[str, ...]
    rows: tuple[tuple[str, ...], ...]
    notes: tuple[str, ...] = field(default_factory=tuple)


SYNTHETIC_BALANCE_SHEET = SyntheticTable(
    title="Synthetic Test Co. Condensed Balance Sheets",
    caption="(in millions; SYNTHETIC TEST DATA)",
    header=("", "As of December 31, 2024", "As of March 31, 2025"),
    rows=(
        ("Cash and cash equivalents", "1,250", "1,310"),
        ("Marketable securities", "2,480", "2,515"),
        ("Accounts receivable, net", "730", "765"),
        ("Total current assets", "4,460", "4,590"),
        ("Property and equipment, net", "3,120", "3,205"),
        ("Total assets", "7,580", "7,795"),
    ),
)

SYNTHETIC_EBITDA_BRIDGE = SyntheticTable(
    title="Reconciliation of Net Income to Adjusted EBITDA (non-GAAP)",
    caption="(in millions; SYNTHETIC TEST DATA)",
    header=("", "Q1 2025", "Q1 2024"),
    rows=(
        ("Net income", "410", "375"),
        ("Interest expense", "35", "38"),
        ("Provision for income taxes", "96", "88"),
        ("Depreciation and amortization", "152", "141"),
        ("Stock-based compensation", "64", "59"),
        ("Adjusted EBITDA", "757", "701"),
    ),
)


def write_synthetic_pdf(path: Path, tables: list[SyntheticTable]) -> Path:
    """Write one table per page into `path` and return it."""
    doc = pymupdf.open()
    for table in tables:
        page = doc.new_page(width=612, height=792)
        page.insert_text((72, 72), table.title, fontsize=13, fontname="helv")
        page.insert_text((72, 92), table.caption, fontsize=9, fontname="helv")
        col_x = [72.0, 300.0, 420.0, 540.0]
        row_h = 22.0
        top = 120.0
        all_rows = [table.header, *table.rows]
        for r, cells in enumerate(all_rows):
            y0 = top + r * row_h
            for c, text in enumerate(cells):
                x0, x1 = col_x[c], col_x[c + 1]
                page.draw_rect(pymupdf.Rect(x0, y0, x1, y0 + row_h), color=(0, 0, 0), width=0.6)
                if not text:
                    continue
                size = 8 if r == 0 else 9.5
                if c == 0:
                    page.insert_text((x0 + 4, y0 + 15), text, fontsize=size, fontname="helv")
                else:
                    width = pymupdf.get_text_length(text, fontname="helv", fontsize=size)
                    page.insert_text((x1 - 6 - width, y0 + 15), text, fontsize=size, fontname="helv")
        for i, note in enumerate(table.notes):
            page.insert_text((72, top + len(all_rows) * row_h + 24 + i * 14), note, fontsize=8)
    path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(path))
    doc.close()
    return path
